### ISSUE TITLE
Figure out how to use Tukio as a replacement for a legacy event system

### ISSUE THREAD

**Issue by JanWennrich** [Crell/Tukio#25]
Hello @Crell,

this is not a real issue but more of a help request to better understand the concept of Listeners, Subscribers, Providers, Dispatcher and how they interact in Tukio.

Feel free to just close the issue without any comment, if the issue tracker should not be used for such requests.

------

After reading your PEAKD articles about PSR-14 and finding out about Tukio, I want to "renovate" the event system in our legacy application. It should follow PSR-14 by using Tukio.

After playing around with Tukio in a test project, I was really happy and thought I could swap out the existing event system easily.

But after further consideration, I have a hard time figuring out if I can/should use Listeners or Subscribers and if multiple Providers are required.

----

Here is a simplified version of how the event system works at the moment:

The current event system is part of a plugin-based application. Every plugin provides an XML file that defines which event should be handled by which class and which static method. It is also possible to specify an event priority/order.

Now on every request the "core" reads all XML files and registers all event listeners.

To fire an event, a method inside the "core" can be called. The "core" then calls all corresponding event listeners.

----

To replace this plugin-based event system with Tukio, I came up with the following approaches:

1. Every plugin has one or more event providers that have to implement the `ListenerProviderInterface`. The XML file then contains a list of those providers. The "core" then uses an `AggregateProvider` to aggregate all providers into one. The `AggregateProvider` is then passed into a `Dispatcher` inside the "core" that can be used to fire an event.
2. Every plugin has one or more `Subscribers`. The XML file then contains a list of those subscribers. The "core" then uses an `OrderedListenerProvider` to add all `Subscribers`. The `OrderedListenerProvider` is then passed into a `Dispatcher` inside the "core" that can be used to fire an event.

But I have the following problems with those approaches:
1. This won't allow me to prioritize/order events (?). I also do not want that plugin developers have to know the `ListenerProviderInterface` and have to come up with their own implementation. 
2. Using `Subscribers` requires a PSR-11 container. Unfortunately the application does not use dependency injection and/or PSR-11 and implementing it would be a lot of effort.

Now I feel like I'm missing something, since both approaches aren't ideal.  
I was imaging a solution where every plugin defines their event listeners as (static) methods by simply using attribute-based registration. The "core" then automagically finds those subscribers and adds them to a central `OrderedListenerProvider`. That provider is then passed into a global `Dispatcher` that can be used to fire events.

Is it true that dependency injection and/or PSR-11 containers would be required for such a solution?  
Is this even an "ideal" solution or is my reasoning affected by the existing legacy concepts?
How would you approach this problem?

Thanks for your time and help in advance.  
I would greatly appreciate any advice.

Best regards,  
Jan

**Comment by Crell** [comment]
Hi Jan.  Let me clarify a few things.

1. Typically, an application will have only one Dispatcher instance, period.  That Dispatcher will have one Provider that it references, period.  That provider *may* in turn delegate to others (eg, via the AggregateProvider in event-dispatcher-utils), but that's not relevant to the application.  You probably do not want to let each plugin have its own Provider, because of exactly the problems you ran into.
2. Tukio supports either runtime-defined set of listeners -- which could be functions, methods on already-instantiated objects, Closures, static methods, or methods on a service object -- or pre-compiled listeners -- which can be functions static methods, or methods on a service object.  The precompiled listeners cannot be objects (including Closures), because it has to be statically-defineable.  In practice, service methods and raw functions are the easiest to use there.  Using the precompiled approach is strongly recommended, as it is *vastly* more performant, especially with the new event optimization.

If your app isn't using DI, then first of all you should fix that. :smile:  That said, the purpose of the container used it just to handle lazy-loading of objects.  They don't *technically* need to DI anything, just get retrieved from something that implements PSR-11.  PSR-11 is dirt simple to implement yourself, if you want, so you could build your own PSR-11 compliant object that does whatever logic you want to pass back an object when requested.

The main question is what form your listeners are in right now.  You say above that they're static methods on classes, which... I think Tukio supports?  I so rarely use static methods I don't recall, but I think so... :smile:

So in that case, you could probably just write an adapter layer that translates your XML files into calls to a provider builder instance and use that to generate a single compiled provider, which you can then inject into the dispatcher at runtime.  That adapter layer would be responsible for reading the priority/before/after/id information from the XML file and calling the appropriate method(s) on the builder.  The existing logic in Tukio would then sort out the, er, sorting.  Pre-specifying the event classes you'll be using is optional, but I would recommend it for performance.

You wouldn't need to use any attributes for this, or the Subscriber interface.

I would also suggest having a look at the new v2 branch.  It's in active development now and has cleaned up a *ton* of code while adding some considerably improved functionality in a more streamlined PHP 8-centric interface.  I'm not quite done with it yet, but it's worth considering experimentally.  Of note, I think long term SubscriberInterface is going to go away.  With attributes and some of the improved service handling I'm building, it's basically vestigial.  It will likely just be soft deprecated in 2.0, hard-deprecated in some later 2.x, and removed in 3.x (if that ever is a thing).  So don't worry about using that.

Hope that helps.

**Comment by JanWennrich** [comment]
Hi @Crell and a happy new year!  
Thank you for your extensive answer!

It helped me to get on the right track. Even if it's a lot of work, I'll try to introduce Dependency Injection first and built on that to tackle other problems.

The event methods look like this at the moment:

```php
class EventHandler
{
    public static function onUserLogin(User $User)
    {
        // do something
    }

    // more event handling methods
}
```

So your adapter approach should work - even with compiled listeners/providers, since all event handling methods are declared static.

On the other hand I'm tempted to throw everything overboard. Introducing DI will probably break many APIs and thus also breaking the event system won't hurt a lot.

Now I'm trying to figure out how to bundle all plugin event listeners into one compiled provider.  
Ideally the "core" generates the compiled provider when a plugin is installed/updated/removed.  
But how is the "core" able to "find" the event listeners?  
Maybe [attribute-based registration](https://github.com/Crell/Tukio?tab=readme-ov-file#attribute-based-registration) is the way to go then?  
Does Tukio automatically scan all files for the `Listener`-attribute or do I have to tell it where to look?   
I think I have to use `$builder->addSubscriber('subscriber', Subscriber::class)` and then all methods with the `Listener`-attribute inside `Subscriber::class` will be added?  
An example about that in the README would be great.

If I have to use the `addSubscriber` approach, then the problem re-appears of how the "core" is able to find all Subscriber classes. So I'd probably have to return to the XML file where every plugin defines it's Subscriber classes?

Best regards,  
Jan

**Comment by Crell** [comment]
If all your listeners right now are static methods, then you technically don't need to use DI for Tukio.  Switching your app to have clean constructor DI is a good thing you should look into doing, but it's not a prerequisite here.

Tukio does not currently include a "scanner" to find arbitrary listeners, in part because listeners could be basically anything.  Such a scanner is possible, but a generic one would be very hard to do performantly.  (The best option would be "look for any method in any class in this directory root that has an attribute on it, and use that", but that's certain to have edge cases where it breaks down badly.  Like, right now the attribute is optional to begin with.)

If you already have the XML files, then you already have a usable index of listeners.  Your adapter code would be something like:

```xml
<listeners>
  <listener class="EventHandler" method="onUserLogin" priority=5 id="user-login" />
  // ...
</listeners>
```

```php
$source = load_xml_into_array_or_something();
foreach ($source as $def) {
  $builder->addListener([$def['class'], $def['method']], $def['priority'], $def['id']);
}

// Compile out the builder here.
```

(Again, I don't recall if that's the right syntax for static methods since I use them so rarely.  Check the test suite.  I'll have to see about making that more obvious in v2.)

If you want to get rid of the XML files, too, then you'll need to replace them with some kind of scanner, which currently Tukio does not include itself as that tends to be framework-specific.
